// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/makgig/factory/internal/handler (interfaces: DBPinger)
//
// Generated by this command:
//
//	mockgen -destination=mock_dbpinger_test.go -package=handler . DBPinger
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBPinger is a mock of DBPinger interface.
type MockDBPinger struct {
	ctrl     *gomock.Controller
	recorder *MockDBPingerMockRecorder
	isgomock struct{}
}

// MockDBPingerMockRecorder is the mock recorder for MockDBPinger.
type MockDBPingerMockRecorder struct {
	mock *MockDBPinger
}

// NewMockDBPinger creates a new mock instance.
func NewMockDBPinger(ctrl *gomock.Controller) *MockDBPinger {
	mock := &MockDBPinger{ctrl: ctrl}
	mock.recorder = &MockDBPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBPinger) EXPECT() *MockDBPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDBPinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBPingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDBPinger)(nil).Ping), ctx)
}
